import {
  ProjectCreatedPayload as ContractsProjectCreatedPayloadSchema,
  ProjectMetaUpdatedPayload as ContractsProjectMetaUpdatedPayloadSchema,
  ProjectDeletedPayload as ContractsProjectDeletedPayloadSchema,
  WorktreeWorkspaceCreatedPayload as ContractsWorktreeWorkspaceCreatedPayloadSchema,
  WorktreeWorkspaceMetaUpdatedPayload as ContractsWorktreeWorkspaceMetaUpdatedPayloadSchema,
  WorktreeWorkspaceLifecycleRequestedPayload as ContractsWorktreeWorkspaceLifecycleRequestedPayloadSchema,
  WorktreeWorkspaceArchivedPayload as ContractsWorktreeWorkspaceArchivedPayloadSchema,
  WorktreeWorkspaceRestoredPayload as ContractsWorktreeWorkspaceRestoredPayloadSchema,
  WorktreeWorkspaceReadyPayload as ContractsWorktreeWorkspaceReadyPayloadSchema,
  WorktreeWorkspaceOperationFailedPayload as ContractsWorktreeWorkspaceOperationFailedPayloadSchema,
  ThreadCreatedPayload as ContractsThreadCreatedPayloadSchema,
  ThreadWorkspaceAssignedPayload as ContractsThreadWorkspaceAssignedPayloadSchema,
  ThreadArchivedPayload as ContractsThreadArchivedPayloadSchema,
  ThreadMetaUpdatedPayload as ContractsThreadMetaUpdatedPayloadSchema,
  ThreadPinnedMessageAddedPayload as ContractsThreadPinnedMessageAddedPayloadSchema,
  ThreadPinnedMessageRemovedPayload as ContractsThreadPinnedMessageRemovedPayloadSchema,
  ThreadPinnedMessageDoneSetPayload as ContractsThreadPinnedMessageDoneSetPayloadSchema,
  ThreadPinnedMessageLabelSetPayload as ContractsThreadPinnedMessageLabelSetPayloadSchema,
  ThreadMarkerAddedPayload as ContractsThreadMarkerAddedPayloadSchema,
  ThreadMarkerRemovedPayload as ContractsThreadMarkerRemovedPayloadSchema,
  ThreadMarkerDoneSetPayload as ContractsThreadMarkerDoneSetPayloadSchema,
  ThreadMarkerLabelSetPayload as ContractsThreadMarkerLabelSetPayloadSchema,
  ThreadRuntimeModeSetPayload as ContractsThreadRuntimeModeSetPayloadSchema,
  ThreadInteractionModeSetPayload as ContractsThreadInteractionModeSetPayloadSchema,
  ThreadDeletedPayload as ContractsThreadDeletedPayloadSchema,
  ThreadUnarchivedPayload as ContractsThreadUnarchivedPayloadSchema,
  ThreadMessageSentPayload as ContractsThreadMessageSentPayloadSchema,
  ThreadProposedPlanUpsertedPayload as ContractsThreadProposedPlanUpsertedPayloadSchema,
  ThreadSessionSetPayload as ContractsThreadSessionSetPayloadSchema,
  ThreadTurnDiffCompletedPayload as ContractsThreadTurnDiffCompletedPayloadSchema,
  ThreadRevertedPayload as ContractsThreadRevertedPayloadSchema,
  ThreadActivityAppendedPayload as ContractsThreadActivityAppendedPayloadSchema,
  ThreadTurnStartRequestedPayload as ContractsThreadTurnStartRequestedPayloadSchema,
  ThreadTurnInterruptRequestedPayload as ContractsThreadTurnInterruptRequestedPayloadSchema,
  ThreadApprovalResponseRequestedPayload as ContractsThreadApprovalResponseRequestedPayloadSchema,
  ThreadCheckpointRevertRequestedPayload as ContractsThreadCheckpointRevertRequestedPayloadSchema,
  ThreadConversationRolledBackPayload as ContractsThreadConversationRolledBackPayloadSchema,
  ThreadConversationRollbackRequestedPayload as ContractsThreadConversationRollbackRequestedPayloadSchema,
  ThreadMessageEditResendRequestedPayload as ContractsThreadMessageEditResendRequestedPayloadSchema,
  ThreadSessionStopRequestedPayload as ContractsThreadSessionStopRequestedPayloadSchema,
} from "@synara/contracts";

// Server-internal alias surface, backed by contract schemas as the source of truth.
export const ProjectCreatedPayload = ContractsProjectCreatedPayloadSchema;
export const ProjectMetaUpdatedPayload = ContractsProjectMetaUpdatedPayloadSchema;
export const ProjectDeletedPayload = ContractsProjectDeletedPayloadSchema;
export const WorktreeWorkspaceCreatedPayload = ContractsWorktreeWorkspaceCreatedPayloadSchema;
export const WorktreeWorkspaceMetaUpdatedPayload =
  ContractsWorktreeWorkspaceMetaUpdatedPayloadSchema;
export const WorktreeWorkspaceLifecycleRequestedPayload =
  ContractsWorktreeWorkspaceLifecycleRequestedPayloadSchema;
export const WorktreeWorkspaceArchivedPayload = ContractsWorktreeWorkspaceArchivedPayloadSchema;
export const WorktreeWorkspaceRestoredPayload = ContractsWorktreeWorkspaceRestoredPayloadSchema;
export const WorktreeWorkspaceReadyPayload = ContractsWorktreeWorkspaceReadyPayloadSchema;
export const WorktreeWorkspaceOperationFailedPayload =
  ContractsWorktreeWorkspaceOperationFailedPayloadSchema;

export const ThreadCreatedPayload = ContractsThreadCreatedPayloadSchema;
export const ThreadWorkspaceAssignedPayload = ContractsThreadWorkspaceAssignedPayloadSchema;
export const ThreadArchivedPayload = ContractsThreadArchivedPayloadSchema;
export const ThreadMetaUpdatedPayload = ContractsThreadMetaUpdatedPayloadSchema;
export const ThreadPinnedMessageAddedPayload = ContractsThreadPinnedMessageAddedPayloadSchema;
export const ThreadPinnedMessageRemovedPayload = ContractsThreadPinnedMessageRemovedPayloadSchema;
export const ThreadPinnedMessageDoneSetPayload = ContractsThreadPinnedMessageDoneSetPayloadSchema;
export const ThreadPinnedMessageLabelSetPayload = ContractsThreadPinnedMessageLabelSetPayloadSchema;
export const ThreadMarkerAddedPayload = ContractsThreadMarkerAddedPayloadSchema;
export const ThreadMarkerRemovedPayload = ContractsThreadMarkerRemovedPayloadSchema;
export const ThreadMarkerDoneSetPayload = ContractsThreadMarkerDoneSetPayloadSchema;
export const ThreadMarkerLabelSetPayload = ContractsThreadMarkerLabelSetPayloadSchema;
export const ThreadRuntimeModeSetPayload = ContractsThreadRuntimeModeSetPayloadSchema;
export const ThreadInteractionModeSetPayload = ContractsThreadInteractionModeSetPayloadSchema;
export const ThreadDeletedPayload = ContractsThreadDeletedPayloadSchema;
export const ThreadUnarchivedPayload = ContractsThreadUnarchivedPayloadSchema;

export const MessageSentPayloadSchema = ContractsThreadMessageSentPayloadSchema;
export const ThreadProposedPlanUpsertedPayload = ContractsThreadProposedPlanUpsertedPayloadSchema;
export const ThreadSessionSetPayload = ContractsThreadSessionSetPayloadSchema;
export const ThreadTurnDiffCompletedPayload = ContractsThreadTurnDiffCompletedPayloadSchema;
export const ThreadRevertedPayload = ContractsThreadRevertedPayloadSchema;
export const ThreadActivityAppendedPayload = ContractsThreadActivityAppendedPayloadSchema;

export const ThreadTurnStartRequestedPayload = ContractsThreadTurnStartRequestedPayloadSchema;
export const ThreadTurnInterruptRequestedPayload =
  ContractsThreadTurnInterruptRequestedPayloadSchema;
export const ThreadApprovalResponseRequestedPayload =
  ContractsThreadApprovalResponseRequestedPayloadSchema;
export const ThreadCheckpointRevertRequestedPayload =
  ContractsThreadCheckpointRevertRequestedPayloadSchema;
export const ThreadConversationRollbackRequestedPayload =
  ContractsThreadConversationRollbackRequestedPayloadSchema;
export const ThreadConversationRolledBackPayload =
  ContractsThreadConversationRolledBackPayloadSchema;
export const ThreadMessageEditResendRequestedPayload =
  ContractsThreadMessageEditResendRequestedPayloadSchema;
export const ThreadSessionStopRequestedPayload = ContractsThreadSessionStopRequestedPayloadSchema;
